### ISSUE TITLE
Theme's are activated after installation

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-wordpress#26]
This probably makes sense when installing only one theme, but most definitely not when installing multiple

**Comment by tersmitten** [comment]
Suggested fix: do not active by default and and add an `active` to do so.

```yaml
themes:
  - name: customizr
    active: true
  - name: profession
```
